// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universidad.Data;

#nullable disable

namespace Universidad.Migrations
{
    [DbContext(typeof(UniversidadDBContext))]
    partial class UniversidadDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Universidad.Models.Curso", b =>
                {
                    b.Property<int>("id_curso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("creditos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("id_curso");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("Universidad.Models.Estudiante", b =>
                {
                    b.Property<int>("id_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_de_inscripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("id_estudiante");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Universidad.Models.Inscripcion", b =>
                {
                    b.Property<int>("id_inscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_curso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_estudiante")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_inscripcion");

                    b.HasIndex("id_curso");

                    b.HasIndex("id_estudiante");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("Universidad.Models.Inscripcion", b =>
                {
                    b.HasOne("Universidad.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("id_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universidad.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("id_estudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Universidad.Models.Curso", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Universidad.Models.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
